# Generated by Django 4.2.7 on 2025-09-28 05:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Brief description or excerpt')),
                ('content', models.TextField(help_text='Full article content')),
                ('read_time', models.CharField(blank=True, max_length=20)),
                ('author', models.CharField(blank=True, default='CareerDisha Team', max_length=100)),
                ('category', models.CharField(choices=[('career_trends', 'Career Trends'), ('job_market', 'Job Market Analysis'), ('skill_development', 'Skill Development'), ('industry_insights', 'Industry Insights'), ('education_guidance', 'Education Guidance'), ('parenting_tips', 'Parenting Tips'), ('interview_tips', 'Interview Tips'), ('personal_development', 'Personal Development'), ('general', 'General')], default='general', max_length=50)),
                ('is_parent_content', models.BooleanField(default=False, help_text='Check if this content is for parents')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('ai_enhanced_content', models.TextField(blank=True, help_text='AI-enhanced version of content')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Upload PDF file (Max 10MB)', upload_to='pdfs/')),
                ('description', models.TextField(blank=True)),
                ('pages', models.CharField(blank=True, max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('career_guides', 'Career Guides'), ('academic_planning', 'Academic Planning'), ('skill_development', 'Skill Development'), ('interview_prep', 'Interview Preparation'), ('college_admission', 'College Admission'), ('parenting_guides', 'Parenting Guides'), ('industry_reports', 'Industry Reports'), ('general', 'General')], default='general', max_length=50)),
                ('is_parent_content', models.BooleanField(default=False, help_text='Check if this content is for parents')),
                ('is_featured', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('ai_generated_summary', models.TextField(blank=True, help_text='AI-generated content summary')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF Resource',
                'verbose_name_plural': 'PDF Resources',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('views', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('medical', 'Medical'), ('business', 'Business'), ('arts', 'Arts & Humanities'), ('science', 'Science'), ('technology', 'Technology'), ('parenting', 'Parenting'), ('career_guidance', 'Career Guidance'), ('education', 'Education'), ('general', 'General')], default='general', max_length=50)),
                ('is_parent_content', models.BooleanField(default=False, help_text='Check if this content is for parents')),
                ('is_featured', models.BooleanField(default=False)),
                ('ai_generated_summary', models.TextField(blank=True, help_text='AI-generated content summary')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Resource',
                'verbose_name_plural': 'Video Resources',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('rating_scale', 'Rating Scale'), ('yes_no', 'Yes/No')], default='multiple_choice', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='resources.careerquiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('career_weight', models.JSONField(default=dict, help_text='Career field weights as JSON')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='resources.quizquestion')),
            ],
        ),
    ]
