# Generated by Django 4.2.7 on 2025-09-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('college_type', models.CharField(choices=[('public', 'Public University'), ('private', 'Private University'), ('community', 'Community College'), ('technical', 'Technical Institute'), ('art', 'Art School'), ('medical', 'Medical College'), ('engineering', 'Engineering College'), ('business', 'Business School')], default='public', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('website', models.URLField()),
                ('established_year', models.IntegerField()),
                ('ranking', models.CharField(blank=True, choices=[('tier1', 'Tier 1 (Top 50)'), ('tier2', 'Tier 2 (51-150)'), ('tier3', 'Tier 3 (151-300)'), ('tier4', 'Tier 4 (300+)')], max_length=50)),
                ('accreditation', models.CharField(blank=True, max_length=200)),
                ('total_students', models.IntegerField(blank=True, null=True)),
                ('acceptance_rate', models.CharField(blank=True, help_text="e.g., '15%', '85%'", max_length=50)),
                ('tuition_fees', models.CharField(blank=True, help_text='Annual tuition fees', max_length=100)),
                ('popular_programs', models.TextField(help_text='Comma-separated list of popular programs')),
                ('admission_requirements', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('campus_facilities', models.TextField(blank=True, help_text='Library, Labs, Sports, etc.')),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-view_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.CharField(help_text="e.g., '$5,000', 'Full tuition', '₹1,00,000'", max_length=100)),
                ('eligibility_criteria', models.TextField()),
                ('application_deadline', models.DateField()),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit-based'), ('need', 'Need-based'), ('sports', 'Sports'), ('minority', 'Minority'), ('subject_specific', 'Subject-specific'), ('government', 'Government'), ('private', 'Private')], default='merit', max_length=50)),
                ('education_level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma'), ('all_levels', 'All Levels')], default='undergraduate', max_length=50)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_website', models.URLField(blank=True)),
                ('application_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('application_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
