import os
import django

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'careerdisha_backend.settings')
django.setup()

from resources.models import College
from datetime import date

# Create 15 Real Colleges
colleges_data = [
    {
        "name": "Indian Institute of Technology Delhi (IIT Delhi)",
        "description": "IIT Delhi is one of the premier engineering institutions in India, established in 1961. It offers undergraduate, postgraduate and doctoral programs in engineering, sciences and technology.",
        "college_type": "engineering",
        "location": "New Delhi",
        "state": "Delhi",
        "country": "India",
        "established_year": 1961,
        "ranking": "top_10",
        "accreditation": "NAAC A++, NBA Accredited",
        "total_students": 8500,
        "tuition_fees": 350000.00,
        "acceptance_rate": 2.5,
        "popular_programs": "Computer Science, Electrical Engineering, Mechanical Engineering, Chemical Engineering",
        "admission_requirements": "JEE Advanced qualification, minimum 75% in 12th standard",
        "website": "https://www.iitd.ac.in/",
        "contact_email": "admissions@iitd.ac.in",
        "contact_phone": "+91-11-2659-1785",
        "campus_facilities": "Hostels, Library, Sports Complex, Research Labs, Medical Center, Wi-Fi Campus",
        "is_featured": True
    },
    {
        "name": "All India Institute of Medical Sciences Delhi (AIIMS Delhi)",
        "description": "AIIMS Delhi is India's premier medical institution, established in 1956. It is renowned for medical education, research and patient care.",
        "college_type": "medical",
        "location": "New Delhi",
        "state": "Delhi", 
        "country": "India",
        "established_year": 1956,
        "ranking": "top_10",
        "accreditation": "Medical Council of India (MCI) Approved",
        "total_students": 3500,
        "tuition_fees": 5000.00,
        "acceptance_rate": 0.8,
        "popular_programs": "MBBS, MD, MS, MCh, DM, B.Sc Nursing",
        "admission_requirements": "NEET UG/PG qualification based on program",
        "website": "https://www.aiims.edu/",
        "contact_email": "admissions@aiims.ac.in",
        "contact_phone": "+91-11-2658-8500",
        "campus_facilities": "Hospital, Research Centers, Library, Hostels, Sports Complex, Auditoriums",
        "is_featured": True
    },
    {
        "name": "Indian Institute of Management Ahmedabad (IIM Ahmedabad)",
        "description": "IIM Ahmedabad is one of India's top business schools, established in 1961. It offers world-class management education and is consistently ranked among top B-schools globally.",
        "college_type": "management",
        "location": "Ahmedabad",
        "state": "Gujarat",
        "country": "India",
        "established_year": 1961,
        "ranking": "top_10",
        "accreditation": "AACSB, EQUIS Accredited",
        "total_students": 1200,
        "tuition_fees": 2500000.00,
        "acceptance_rate": 1.2,
        "popular_programs": "MBA, Executive MBA, Fellowship Programme in Management",
        "admission_requirements": "CAT score, Work experience, Academic performance",
        "website": "https://www.iima.ac.in/",
        "contact_email": "pgpadm@iima.ac.in",
        "contact_phone": "+91-79-6632-4000",
        "campus_facilities": "Library, Computer Center, Sports Complex, Guest House, Dining Halls",
        "is_featured": True
    },
    {
        "name": "University of Delhi (DU)",
        "description": "University of Delhi is one of India's largest and most prestigious universities, established in 1922. It offers diverse undergraduate and postgraduate programs.",
        "college_type": "university",
        "location": "New Delhi",
        "state": "Delhi",
        "country": "India", 
        "established_year": 1922,
        "ranking": "top_50",
        "accreditation": "NAAC A+ Grade, UGC Recognition",
        "total_students": 132000,
        "tuition_fees": 15000.00,
        "acceptance_rate": 45.0,
        "popular_programs": "Arts, Science, Commerce, Law, Education, Management",
        "admission_requirements": "CUET UG/PG based on program, 12th standard completion",
        "website": "https://www.du.ac.in/",
        "contact_email": "info@du.ac.in",
        "contact_phone": "+91-11-2766-7049",
        "campus_facilities": "Multiple Libraries, Sports Facilities, Cultural Centers, Hostels, Canteens",
        "is_featured": True
    },
    {
        "name": "Jawaharlal Nehru University (JNU)",
        "description": "JNU is a prestigious central university known for its academic excellence and research in social sciences, languages, and international studies.",
        "college_type": "university",
        "location": "New Delhi",
        "state": "Delhi",
        "country": "India",
        "established_year": 1969,
        "ranking": "top_50",
        "accreditation": "NAAC A+ Grade",
        "total_students": 8500,
        "tuition_fees": 2000.00,
        "acceptance_rate": 15.0,
        "popular_programs": "International Studies, Social Sciences, Languages, Science, Engineering",
        "admission_requirements": "JNU Entrance Exam (JNUEE), qualifying degree",
        "website": "https://www.jnu.ac.in/",
        "contact_email": "registrar@mail.jnu.ac.in",
        "contact_phone": "+91-11-2670-4000",
        "campus_facilities": "Central Library, Computer Centers, Sports Complex, Cultural Centers, Hostels",
        "is_featured": False
    },
    {
        "name": "Banaras Hindu University (BHU)",
        "description": "BHU is one of India's largest residential universities, established in 1916. It offers comprehensive education across various disciplines.",
        "college_type": "university",
        "location": "Varanasi",
        "state": "Uttar Pradesh",
        "country": "India",
        "established_year": 1916,
        "ranking": "top_50",
        "accreditation": "NAAC A++ Grade",
        "total_students": 27000,
        "tuition_fees": 20000.00,
        "acceptance_rate": 25.0,
        "popular_programs": "Engineering, Medicine, Arts, Science, Agriculture, Law",
        "admission_requirements": "BHU UET/PET based on program",
        "website": "https://www.bhu.ac.in/",
        "contact_email": "registrar@bhu.ac.in", 
        "contact_phone": "+91-542-230-7309",
        "campus_facilities": "Vishwanath Temple, Museum, Library, Sports Facilities, Hostels, Medical Facilities",
        "is_featured": False
    },
    {
        "name": "Indian Institute of Science Bangalore (IISc)",
        "description": "IISc is India's premier institute for advanced scientific and technological research and education, established in 1909.",
        "college_type": "engineering",
        "location": "Bangalore",
        "state": "Karnataka", 
        "country": "India",
        "established_year": 1909,
        "ranking": "top_10",
        "accreditation": "NAAC A++ Grade, NBA Accredited",
        "total_students": 4000,
        "tuition_fees": 65000.00,
        "acceptance_rate": 3.0,
        "popular_programs": "Research in Science and Engineering, Integrated PhD, MTech",
        "admission_requirements": "GATE/NET/JEE Advanced/KVPY for different programs",
        "website": "https://www.iisc.ac.in/",
        "contact_email": "office.registrar@iisc.ac.in",
        "contact_phone": "+91-80-2293-2001",
        "campus_facilities": "Research Labs, Library, Sports Complex, Guest House, Gym, Swimming Pool",
        "is_featured": True
    },
    {
        "name": "National Law School of India University (NLSIU)",
        "description": "NLSIU is India's premier law school, established in 1986. It has revolutionized legal education in India.",
        "college_type": "law",
        "location": "Bangalore",
        "state": "Karnataka",
        "country": "India",
        "established_year": 1986,
        "ranking": "top_10",
        "accreditation": "Bar Council of India Approved, NAAC A++ Grade",
        "total_students": 800,
        "tuition_fees": 300000.00,
        "acceptance_rate": 2.0,
        "popular_programs": "BA LLB (Hons), LLM, PhD in Law",
        "admission_requirements": "CLAT qualification, minimum academic requirements",
        "website": "https://www.nls.ac.in/",
        "contact_email": "registrar@nls.ac.in",
        "contact_phone": "+91-80-2341-1160",
        "campus_facilities": "Moot Court, Legal Aid Clinic, Library, Sports Facilities, Hostels",
        "is_featured": False
    },
    {
        "name": "Indian Statistical Institute (ISI)",
        "description": "ISI is a premier institute for research and education in statistics, mathematics, and allied fields, established in 1931.",
        "college_type": "university",
        "location": "Kolkata",
        "state": "West Bengal",
        "country": "India",
        "established_year": 1931,
        "ranking": "top_50",
        "accreditation": "Deemed University Status",
        "total_students": 2000,
        "tuition_fees": 45000.00,
        "acceptance_rate": 8.0,
        "popular_programs": "Statistics, Mathematics, Computer Science, Economics",
        "admission_requirements": "ISI Admission Test, qualifying degree",
        "website": "https://www.isical.ac.in/",
        "contact_email": "registrar@isical.ac.in",
        "contact_phone": "+91-33-2575-2001",
        "campus_facilities": "Research Centers, Library, Computer Labs, Guest House, Sports Facilities",
        "is_featured": False
    },
    {
        "name": "Tata Institute of Fundamental Research (TIFR)",
        "description": "TIFR is a premier research institution in fundamental sciences, established in 1945 by Dr. Homi Bhabha.",
        "college_type": "university",
        "location": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "established_year": 1945,
        "ranking": "top_50",
        "accreditation": "Deemed University Status",
        "total_students": 1500,
        "tuition_fees": 25000.00,
        "acceptance_rate": 5.0,
        "popular_programs": "Physics, Mathematics, Biology, Computer Science, Chemistry",
        "admission_requirements": "TIFR GS Examination, strong academic background",
        "website": "https://www.tifr.res.in/",
        "contact_email": "academic@tifr.res.in",
        "contact_phone": "+91-22-2278-2000",
        "campus_facilities": "Advanced Research Labs, Library, Auditoriums, Hostels, Recreation Facilities",
        "is_featured": False
    },
    {
        "name": "Jamia Millia Islamia University",
        "description": "Jamia is a central university established in 1920, known for its inclusive approach to education and diverse academic programs.",
        "college_type": "university",
        "location": "New Delhi",
        "state": "Delhi",
        "country": "India",
        "established_year": 1920,
        "ranking": "top_100",
        "accreditation": "NAAC A Grade",
        "total_students": 17000,
        "tuition_fees": 12000.00,
        "acceptance_rate": 30.0,
        "popular_programs": "Engineering, Architecture, Humanities, Social Sciences, Education",
        "admission_requirements": "JMI Entrance Test, qualifying degree based on program",
        "website": "https://www.jmi.ac.in/",
        "contact_email": "registrar@jmi.ac.in",
        "contact_phone": "+91-11-2698-1717",
        "campus_facilities": "Central Library, Mosque, Sports Complex, Medical Center, Hostels",
        "is_featured": False
    },
    {
        "name": "Aligarh Muslim University (AMU)",
        "description": "AMU is a residential academic institution established in 1875, offering over 300 courses across various disciplines.",
        "college_type": "university",
        "location": "Aligarh",
        "state": "Uttar Pradesh",
        "country": "India",
        "established_year": 1875,
        "ranking": "top_100",
        "accreditation": "NAAC A+ Grade",
        "total_students": 28000,
        "tuition_fees": 15000.00,
        "acceptance_rate": 40.0,
        "popular_programs": "Medicine, Engineering, Arts, Science, Law, Management",
        "admission_requirements": "AMU Entrance Test based on program",
        "website": "https://www.amu.ac.in/",
        "contact_email": "registrar@amu.ac.in",
        "contact_phone": "+91-571-270-0920",
        "campus_facilities": "Maulana Azad Library, Medical College, Sports Facilities, Guest Houses, Museums",
        "is_featured": False
    },
    {
        "name": "Hyderabad Central University",
        "description": "Also known as University of Hyderabad, it's a premier central university established in 1974, known for research and quality education.",
        "college_type": "university",
        "location": "Hyderabad", 
        "state": "Telangana",
        "country": "India",
        "established_year": 1974,
        "ranking": "top_100",
        "accreditation": "NAAC A++ Grade",
        "total_students": 5000,
        "tuition_fees": 8000.00,
        "acceptance_rate": 20.0,
        "popular_programs": "Science, Social Sciences, Humanities, Engineering, Management",
        "admission_requirements": "Entrance test based on program, qualifying degree",
        "website": "https://www.uohyd.ac.in/",
        "contact_email": "registrar@uohyd.ernet.in",
        "contact_phone": "+91-40-2313-4000",
        "campus_facilities": "Central Library, Health Center, Sports Complex, Guest House, Shopping Complex",
        "is_featured": False
    },
    {
        "name": "Birla Institute of Technology and Science (BITS Pilani)",
        "description": "BITS Pilani is a prestigious private technical university established in 1964, known for quality engineering education.",
        "college_type": "engineering",
        "location": "Pilani",
        "state": "Rajasthan",
        "country": "India",
        "established_year": 1964,
        "ranking": "top_50",
        "accreditation": "NAAC A Grade, NBA Accredited",
        "total_students": 15000,
        "tuition_fees": 450000.00,
        "acceptance_rate": 12.0,
        "popular_programs": "Engineering, Pharmacy, Management, Sciences",
        "admission_requirements": "BITSAT examination, 12th standard with PCM",
        "website": "https://www.bits-pilani.ac.in/",
        "contact_email": "admissions@pilani.bits-pilani.ac.in",
        "contact_phone": "+91-1596-242-531",
        "campus_facilities": "Library, Labs, Sports Complex, Hostels, Medical Center, Auditoriums",
        "is_featured": True
    },
    {
        "name": "National Institute of Technology Trichy (NIT Trichy)",
        "description": "NIT Trichy is one of the premier engineering institutions in India, established in 1964 as Regional Engineering College.",
        "college_type": "engineering", 
        "location": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "country": "India",
        "established_year": 1964,
        "ranking": "top_50",
        "accreditation": "NAAC A++ Grade, NBA Accredited",
        "total_students": 9000,
        "tuition_fees": 180000.00,
        "acceptance_rate": 6.0,
        "popular_programs": "Computer Science, Electronics, Mechanical, Civil Engineering",
        "admission_requirements": "JEE Main qualification, minimum 75% in 12th standard",
        "website": "https://www.nitt.edu/",
        "contact_email": "dean_acad@nitt.edu",
        "contact_phone": "+91-431-250-3000",
        "campus_facilities": "Central Library, Research Centers, Sports Complex, Hostels, Medical Center",
        "is_featured": True
    }
]

# Create colleges
for college_data in colleges_data:
    college = College.objects.create(**college_data)
    print(f"Created college: {college.name}")

print(f"Created {len(colleges_data)} colleges successfully!")